---
title: "Diffusion Profiles"
author: "John C. Ayers"
output:
  html_document:
    df_print: paged
---

```{r set-global, include=FALSE, echo=FALSE}
# Suppress all error messages
knitr::opts_chunk$set(error = FALSE)
```

```{r}
library(tidyverse)
Diffusion <- read_csv("DiffusionProfilesV3.csv")
DiffusionLong <- Diffusion %>%
  pivot_longer(c("SiO2":"TiO2"), names_to = "Oxide", values_to = "Value")
ExptList <- unique(DiffusionLong$Expt)
```

Plot diffusion profiles for each dissolution experiment. Profiles for experiment SpDis13 are Figure 2 in manuscript.

```{r}
for (i in seq_along(ExptList)) {
  tmp <- filter(DiffusionLong, Expt == ExptList[i])
print(ggplot(tmp, aes(x = x, y = Value)) +
  geom_point() +
  geom_smooth(level=0.95) +
  facet_wrap(facets = vars(Oxide), scales = "free_y") +
  xlab("Distance from titanite crystal (μm)") +
  ylab("Oxide concentration (wt. %)") +
  theme_bw()
)
print(paste(str_c("Experiment ", ExptList[i])))
}
```

Create manuscript Figure 6: TiO2 raw and linearized diffusion profiles for experiment SpDis12

```{r}
DiffProf <- read_csv("SpDis12TiO2DiffusionProfile.csv")
print(ggplot(DiffProf, aes(x = x, y = TiO2)) +
  geom_point() +
  geom_smooth() +
  xlab("Distance from titanite crystal (μm)") +
  ylab("TiO2 concentration (wt. %)") +
  theme_bw()
)
print(ggplot(DiffProf, aes(x=x, y = InvTiO2)) +
  geom_point() +
  geom_smooth(method = lm, color = "brown", se = TRUE, level = 0.95) +
  theme_bw() +
  xlab("Distance from titanite crystal (μm)") +
  ylab(bquote(TiO[2] ~erf^{"-1"}~"(1 - Cx/C0)"))
  )
```
 ylab(bquote(~TiO[2]~))
"(1 – "~C[x]~"/"~C[0]~")"
