---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse, warn.conflicts = FALSE)
setwd("C:/Users/ayersj/OneDrive - Vanderbilt/Papers/SpheneSolubility/DataAnalysis/TitaniteExpts")
# Import MELTS model results
MELTSresultsV2 <- read_csv("MELTSresultsV2.csv")

```


```{r}
# Convert oxides to cation concentrations
MELTSCations <- MELTSresultsV2 %>%
  mutate(
    Si = SiO2/60.0848,
    Al = 2*Al2O3/101.961,
    Na = 2*Na2O/61.979,
    K = 2*K2O/94.194,
    Ca = CaO/56.0794,
    Fe = FeO/71.8464,
    Mg = MgO/40.3044,
    Ti = TiO2/79.8988,
    Mn = MnO/70.9374,
    P = 2*P2O5/141.945,
    CationSum = (Si + Al + Na + K + Ca + Fe + Mg + Ti + Mn + P)
             )
```

```{r}
# Calculate cation fractions
CationFractions <- select(MELTSCations, Expt, SM, TC, Pkb, Titanite, H2O, TiO2, Si:CationSum)
f <- match("Si", names(CationFractions))
l <- match("P", names(CationFractions))
for (i in f:l) {
  CationFractions[(i)] = CationFractions[(i)]/CationFractions$CationSum
}

```

```{r}
# Calculate melt composition parameters
CationFractions <- filter(CationFractions, Titanite == "Y" | Titanite == "Y (+ rutile)")%>%
  mutate(
    M = (Na + K + 2*Ca)/(Si*Al),
    FM = (Na + K + 2*(Ca + Fe + Mg))/(Si*Al),
    TK = TC+273.15,
    InvTK = 1/TK,
    PInvTK = (Pkb*1000 - 1)*InvTK
    )
```

```{r}
# Correlation matrix
CorrTest <- select(CationFractions, TiO2, H2O, Ca, Al, M:PInvTK)
cor(CorrTest)
# MELTS liquid TiO2 concentration is most highly correlated with TK, H2O, and FM.
# Scatterplot matrices
library(car)
scatterplotMatrix(~ Ti + Ca + H2O + InvTK + TK + M + FM, data = CationFractions, smooth = FALSE)

```

```{r}
library(leaps)
leaps <- regsubsets(TiO2 ~ TK + H2O + Ca + M + FM + InvTK, data = CationFractions, nbest = 2) 
plot(leaps, scale = "adjr2")
# summary(leaps)
```

```{r}
fit <- lm(TiO2 ~ Ca + H2O, data = CationFractions)
summary(fit)

```

```{r}
# MELTS Ti concentrations show very different dependencies than Flanagan growth experiments. 
```

