---
title: 'Titanite solubility experiments: Analysis of EDS data'
author: "John C. Ayers"
output:
  html_document:
    df_print: paged
---

```{r}
library(tidyverse, warn.conflicts = FALSE)
setwd("C:/Users/ayersj/OneDrive - Vanderbilt/Papers/SpheneSolubility/DataAnalysis/TitaniteExpts")
# Import normalized EDS glass analyses
TitaniteExpts <- read_csv("TitaniteExptsV2.csv")
```
```{r}
# Convert oxides to cation concentrations
TitaniteCations <- TitaniteExpts %>%
  mutate(
    Si = SiO2/60.0848,
    Al = 2*Al2O3/101.961,
    Na = 2*Na2O/61.979,
    K = 2*K2O/94.194,
    Ca = CaO/56.0794,
    Fe = FeO/71.8464,
    Mg = MgO/40.3044,
    Ti = TiO2/79.8988,
    Mn = MnO/70.9374,
    P = 2*P2O5/141.945,
    CationSum = (Si + Al + Na + K + Ca + Fe + Mg + Ti + Mn + P)
             )
```

```{r}
# Calculate cation fractions
CationFractions <- select(TitaniteCations, Expt, Type, SM, TC, Pkb, H2O, TimeH, Titanite, Rutile, TiO2, Si:CationSum)
f <- match("Si", names(CationFractions))
l <- match("P", names(CationFractions))
for (i in f:l) {
  CationFractions[(i)] = CationFractions[(i)]/CationFractions$CationSum
}

```


```{r}
# Calculate melt composition parameters
CationFractions <- CationFractions %>%
  mutate(
    M = (Na + K + 2*Ca)/(Si*Al),
    FM = (Na + K + 2*(Ca + Fe + Mg))/(Si*Al),
    TK = TC+273.15,
    InvTK = 1/TK,
    PInvTK = (Pkb*1000 - 1)*InvTK
    )
```


```{r}
NoTitanite <- filter(CationFractions, Titanite == "N")
CationFractionsTitanite <- filter(CationFractions, Titanite == "Y")
# Plot time series
CationFractionsTitanite$Isotherm <- factor(CationFractionsTitanite$TC)
SMplot <- c("GSP + AGV", "PST", "GSP")
for (i in seq_along(SMplot)) {
  Comp <- filter(CationFractionsTitanite, SM == SMplot[i])
p <- ggplot(Comp, aes(x=TimeH, y=TiO2, shape=Isotherm, color=Isotherm)) +
  geom_point() +
  labs(title = as.name(SMplot[i]))
print(p)
}
# Time series a bit concerning, since many isotherms seem to have a negative slope, suggesting that titanite crystallization is kinetically inhibited.
```

```{r}
# Correlation matrix
CorrTest <- select(CationFractionsTitanite, TiO2, TimeH, Pkb, H2O, Ca,  M:PInvTK)
cor(CorrTest)
# Glass TiO2 concentration is positively correlated with melt composition parameter M and TK and negatively correlated with time and InvTK. 
# Scatterplot matrices
library(car)
CationFractionsTitanite$Type <- factor(CationFractionsTitanite$Type)
scatterplotMatrix(~ Ti + Ca + TimeH + InvTK + TK + M, data = CationFractionsTitanite, smooth = FALSE)
```


```{r}
library(leaps)
leaps <- regsubsets(TiO2 ~ TC + Pkb + H2O + M + FM + InvTK, data = CationFractionsTitanite, nbest = 2) 
plot(leaps, scale = "adjr2")
# summary(leaps)
```


```{r}
fit <- lm(TiO2 ~ M + InvTK + Pkb, data = CationFractionsTitanite)
summary(fit)

```

```{r}
# Pkb is not significant, so drop
fit <- lm(TiO2 ~ M + InvTK, data = CationFractionsTitanite)
summary(fit)
plot(fit)
```


```{r}
RegModel <- select(CationFractionsTitanite, Expt, Type, TiO2, InvTK, M)
DelExpts <- c("SpDis_1", "SpDis_2", "SpDis_4")
RegModel <- filter(RegModel, !(Expt %in%  DelExpts))
fit <- lm(TiO2 ~ M + InvTK, data = RegModel)
summary(fit)
plot(fit)
# I think this is our best model. Removing more experiments doesn't significantly improve fit.
write.csv(RegModel, "ExptsInModel.csv")
```

```{r}
# Calculate model TiO2 concentrations and errors
RegModel <- RegModel %>%
  mutate(
   TiO2saturation = (3.47*M - 8868*InvTK + 3.47),
   TiO2saturationSD = TiO2saturation*sqrt((0.22/3.47)^2 + (1575/8868)^2),
   lower = TiO2saturation - TiO2saturationSD,
   upper = TiO2saturation + TiO2saturationSD
  )
```

```{r}
library(plotly)
ggplot(RegModel, aes(x=TiO2, y=TiO2saturation, ymin=lower, ymax=upper, shape = Type, color = Type)) +
  geom_pointrange() +
  geom_abline(slope=1, intercept=0)
# Convert it to an interactive plot
ggplotly()
```

```{r}
# log-log plot
ggplot(RegModel, aes(x=log(TiO2), y=log(TiO2saturation), ymin=log(lower), ymax=log(upper), shape = Type, color = Type)) +
  geom_pointrange() +
  geom_abline(slope=1, intercept=0)
```


```{r}
ggplot(RegModel, aes(x=M, y=TiO2, shape = Type, color = Type)) +
  geom_point()
```

```{r}
# Create model output table
TiO2ModelTable <- select(RegModel, Expt, M, InvTK, TiO2, TiO2saturation, TiO2saturationSD)
write.csv(TiO2ModelTable, file = "TiO2ModelTable.csv")
```

```{r}
# Use Model equation to test whether Expts in "NoTitanite" are undersaturated
NoTitaniteModel <- filter(NoTitanite, Rutile == "N") %>%
  mutate(
   TiO2saturation = (3.47*M - 8868*InvTK + 3.47),
   TiO2saturationSD = TiO2saturation*sqrt((0.22/3.47)^2 + (1575/8868)^2),
   lower = TiO2saturation - TiO2saturationSD,
   upper = TiO2saturation + TiO2saturationSD
  )

CompareTiO2 <- select(NoTitaniteModel, Expt, TiO2, TiO2saturation)
CompareTiO2
# NoTitaniteModel <- NoTitaniteModel%>%
#   add_column(Agree = "?")
# # Don't know why "N" is assigned but not "Y" in following loop
# for (i in 1:nrow(NoTitaniteModel)) {
#   if (NoTitaniteModel$TiO2saturation[i] > NoTitaniteModel$TiO2[i]) {
#     NoTitanite$Agree[i] <- c("Y")
#   }
#   else {
#     NoTitaniteModel$Agree[i] <- c("N")
#   }
# }
```


