---
title: 'Titanite solubility experiments: Analysis of EDS data'
author: "John C. Ayers"
output:
  html_document:
    df_print: paged
---

```{r}
library(tidyverse, warn.conflicts = FALSE)
setwd("C:/Users/ayersj/OneDrive - Vanderbilt/Papers/SpheneSolubility/DataAnalysis/TitaniteExpts")
# Import normalized EDS glass analyses
TitaniteExpts <- read_csv("TitaniteExpts.csv")
```
```{r}
TitaniteCations <- TitaniteExpts %>%
  mutate(
    Si = SiO2/60.0848,
    Al = 2*Al2O3/101.961,
    Na = 2*Na2O/61.979,
    K = 2*K2O/94.194,
    Ca = CaO/56.0794,
    Fe = FeO/71.8464,
    Mg = MgO/40.3044,
    Ti = TiO2/79.8988,
    Mn = MnO/70.9374,
    P = 2*P2O5/141.945,
    eCa = (CaO/56.0794 - Al2O3/101.961 + K2O/94.194 + Na2O/61.979),
    CationSum = (Si + Al + Na + K + Ca + Fe + Mg + Ti + Mn + P)
             )
```

```{r}
# Calculate cation fractions
CationFractions <- select(TitaniteCations, Model, Expt, SM, TC, Pkb, H2O, TiO2, Si:eCa, CationSum)
f <- match("Si", names(CationFractions))
l <- match("eCa", names(CationFractions))
for (i in f:l) {
  CationFractions[(i)] = CationFractions[(i)]/CationFractions$CationSum
}

```


```{r}
# Calculate melt composition parameters
CationFractions <- CationFractions %>%
  mutate(
    M = (Na + K + 2*Ca)/(Si*Al),
    FM = (Na + K + 2*(Ca + Fe + Mg))/(Si*Al),
    C = (10*eCa)/(Si*Al),
    InvTK = 1/(TC+273.15)
    )
```


```{r}
# Scatterplot matrices
library(car)
scatterplotMatrix(~ Ti + Ca + Al + InvTK + M + FM + C, data = CationFractions, groups = CationFractions$Model, smooth = FALSE)
# Correlation matrix
CorrTest <- select(CationFractions, TiO2, M:InvTK)
cor(CorrTest)
# Glass TiO2 concentration is most highly correlated with melt composition parameter C.

```

```{r}
fit <- lm(TiO2 ~ C + InvTK, data = CationFractions)
summary(fit)
plot(fit)

```

```{r}
# Experiments 29, 30 & 31 are identified as outliers. They were Danny's earliest experiments, and were all run at 1300C.

RegModel <- select(CationFractions, Model, Expt, TiO2, InvTK, C)
RegModel <- slice(RegModel, -(29:31))
fit <- lm(TiO2 ~ C + InvTK, data = RegModel)
summary(fit)
plot(fit)

```

```{r}
# Experiments in rows 28, 29 are outliers.
RegModel <- slice(RegModel, -(28:29))
fit <- lm(TiO2 ~ C + InvTK, data = RegModel)
summary(fit)
plot(fit)
# I think this is our best model. Removing more experiments doesn't significantly improve fit.
write.csv(RegModel, "ExptsInModel.csv")
```

```{r}
# Try filtering out experiments with Model = "N"
RegModel <- select(CationFractions, Model, Expt, TiO2, InvTK, C)
RegModel <- filter(RegModel, Model == "Y")
fit <- lm(TiO2 ~ C + InvTK, data = RegModel)
summary(fit)
plot(fit)
# 6 fewer experiments increases r^2 to 0.98
```
```{r}
# Calculate model TiO2 concentrations and errors
CationFractions <- CationFractions %>%
  mutate(
   ModelTiO2 = (0.79*C - 7996*InvTK + 7.888),
   ModelTiO2SD = ModelTiO2*sqrt((0.03514/0.79)^2 + (1243/7996)^2)
  )
```

```{r}
# Create model output table
TiO2ModelTable <- select(CationFractions, Model, Expt, eCa, C, InvTK, TiO2, ModelTiO2, ModelTiO2SD)
write.csv(TiO2ModelTable, file = "TiO2ModelTable.csv")
```

